[phases.setup]
nixPkgs = ["php", "apacheHttpd"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-reqs"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "httpd -f /var/www/html/conf/httpd.conf -D FOREGROUND"